spring:
  application:
    name: newunion
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QinZhiWenXuan/newunion
      label: master
management:
  context-path: /admin   